const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getPathForFile: (file) =>
    webUtils && webUtils.getPathForFile ? webUtils.getPathForFile(file) : file.path,
  confirmClose: (data) => ipcRenderer.invoke('confirm-close', data),
  closeConfirmed: () => ipcRenderer.send('close-confirmed'),
  showError: (data) => ipcRenderer.invoke('show-error', data),
  onRequestClose: (callback) => ipcRenderer.on('request-close', () => callback()),
  openFile: () => ipcRenderer.invoke('dialog-open'),
  openFolder: () => ipcRenderer.invoke('dialog-open-folder'),
  saveAs: (data) => ipcRenderer.invoke('dialog-save-as', data),
  saveFile: (data) => ipcRenderer.invoke('file-save', data),
  readFile: (data) => ipcRenderer.invoke('file-read', data),
  readDirectory: (data) => ipcRenderer.invoke('read-directory', data),
  getRecentFiles: () => ipcRenderer.invoke('get-recent-files'),
  trackRecentFile: (data) => ipcRenderer.invoke('track-recent-file', data),
  setTitle: (data) => ipcRenderer.invoke('set-title', data),
  checkGrammar: (data) => ipcRenderer.invoke('check-grammar', data),
  saveSession: (data) => ipcRenderer.send('save-session', data),

  onFileOpened: (callback) => ipcRenderer.on('file-opened', (event, data) => callback(data)),
  onFolderOpened: (callback) => ipcRenderer.on('folder-opened', (event, data) => callback(data)),
  onMenuNew: (callback) => ipcRenderer.on('menu-new', () => callback()),
  onMenuSave: (callback) => ipcRenderer.on('menu-save', () => callback()),
  onMenuSaveAs: (callback) => ipcRenderer.on('menu-save-as', () => callback()),
  onMenuUndo: (callback) => ipcRenderer.on('menu-undo', () => callback()),
  onMenuRedo: (callback) => ipcRenderer.on('menu-redo', () => callback()),
  onMenuFind: (callback) => ipcRenderer.on('menu-find', () => callback()),
  onMenuReplace: (callback) => ipcRenderer.on('menu-replace', () => callback()),
  onMenuGotoLine: (callback) => ipcRenderer.on('menu-goto-line', () => callback()),
  onMenuToggleWrap: (callback) => ipcRenderer.on('menu-toggle-wrap', () => callback()),
  onMenuToggleSidebar: (callback) => ipcRenderer.on('menu-toggle-sidebar', () => callback()),
  onMenuToggleMinimap: (callback) => ipcRenderer.on('menu-toggle-minimap', () => callback()),
  onMenuFoldAll: (callback) => ipcRenderer.on('menu-fold-all', () => callback()),
  onMenuUnfoldAll: (callback) => ipcRenderer.on('menu-unfold-all', () => callback()),
  onMenuZoomIn: (callback) => ipcRenderer.on('menu-zoom-in', () => callback()),
  onMenuZoomOut: (callback) => ipcRenderer.on('menu-zoom-out', () => callback()),
  onMenuZoomReset: (callback) => ipcRenderer.on('menu-zoom-reset', () => callback()),
  onMenuTransform: (callback) => ipcRenderer.on('menu-transform', (event, type) => callback(type)),
  onMenuLineOp: (callback) => ipcRenderer.on('menu-line-op', (event, type) => callback(type)),
  onMenuToggleSplit: (callback) => ipcRenderer.on('menu-toggle-split', () => callback()),
  onMenuToggleTheme: (callback) => ipcRenderer.on('menu-toggle-theme', () => callback()),
  onRestoreSession: (callback) => ipcRenderer.on('restore-session', (event, data) => callback(data)),
});
